// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonTeamPlanner;

#nullable disable

namespace PokemonTeamPlanner.Migrations
{
    [DbContext(typeof(TeamPlannerContext))]
    [Migration("20260529153611_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("PokemonTeamPlanner.PokemonEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<int?>("PokemonTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("url");

                    b.HasKey("Id");

                    b.HasIndex("PokemonTeamId");

                    b.ToTable("PokemonEntries");

                    b.HasAnnotation("Relational:JsonPropertyName", "team_members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bulbasaur",
                            Url = "https://pokeapi.co/api/v2/pokemon/1/"
                        });
                });

            modelBuilder.Entity("PokemonTeamPlanner.PokemonTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.HasKey("Id");

                    b.ToTable("PokemonTeams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Test team for development purposes.",
                            Name = "Test Team"
                        });
                });

            modelBuilder.Entity("PokemonTeamPlanner.PokemonEntry", b =>
                {
                    b.HasOne("PokemonTeamPlanner.PokemonTeam", null)
                        .WithMany("TeamMembers")
                        .HasForeignKey("PokemonTeamId");
                });

            modelBuilder.Entity("PokemonTeamPlanner.PokemonTeam", b =>
                {
                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
